### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by dftoro** [bradmartin/nativescript-floatingactionbutton#17]
Hi Brad, this widget  is great !!!

I'm trying to use floatingactionbutton, but I have a error in runtime.

I made 
1.  npm install nativescript-floatingactionbutton
2. Insert XML  and CSS code like your example
3. tns run android

tns --version:  1.5.2

Error trace:
========================
com.tns.NativeScriptException: 
Calling js method onClick failed

Error: Building UI from XML. @file:///app/componentes/entrega/cumplidoImg.xml:17:12
 ���Module '/data/data/org.nativescript.logiApp/files/app/tns_modules/nativescript-floatingactionbutton' not found for element 'nativescript-floatingactionbutton:Fab'.
   ���
  Error calling module function 

TypeError: style.StylePropertyChangedHandler is not a function
File: "/data/data/org.nativescript.logiApp/files/app/tns_modules/nativescript-floatingactionbutton/fab.js, line: 77, column: 61

StackTrace: 
	Frame: function:'FloatingActionButtonStyler.registerHandlers', file:'/data/data/org.nativescript.logiApp/files/app/tns_modules/nativescript-floatingactionbutton/fab.js', line: 77, column: 62
	Frame: function:'', file:'/data/data/org.nativescript.logiApp/files/app/tns_modules/nativescript-floatingactionbutton/fab.js', line: 83, column: 28
	Frame: function:'require', file:'', line: 1, column: 120
	Frame: function:'getComponentModule', file:'/data/data/org.
================================

**Comment by bradmartin** [comment]
Can you share your XML (remove any private data/info)? Did you declare the `xmlns` on the XML page? Also these types of errors indicate something is usually wrong with the project. I suggest you try `tns platform remove android` then `tns platform add android` then `npm i nativescript-floatingactionbutton` then see if the error continues. If so I'll try to reproduce it with a demo app. Thanks.

**Comment by lazaromenezes** [comment]
Isn't it related with this https://github.com/bradmartin/nativescript-floatingactionbutton/pull/10?

**Comment by bradmartin** [comment]
On top of @lazaromenezes comment. You should upgrade to {N} 1.6.2 and that should fix your issues.

**Comment by dftoro** [comment]
upgrade 1.6.1 and fixed issue
