### ISSUE TITLE
Build error while compiling java with javac

### ISSUE THREAD

**Issue by t1amat9409** [bradmartin/nativescript-floatingactionbutton#19]
```
:compileNativescriptfloatingactionbuttonDebugJavaWithJavac
/Users/louis/Documents/Projects/float/platforms/android/build/generated/source/r/nativescriptfloatingactionbutton/debug/org/nativescript/float/R.java:8: error: <identifier> expected
package org.nativescript.float;
                         ^
/Users/louis/Documents/Projects/float/platforms/android/build/generated/source/buildConfig/nativescriptfloatingactionbutton/debug/org/nativescript/float/BuildConfig.java:4: error: <identifier> expected
package org.nativescript.float;
                         ^
2 errors
:compileNativescriptfloatingactionbuttonDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileNativescriptfloatingactionbuttonDebugJavaWithJavac'.

```

**Comment by bradmartin** [comment]
@t1amat9409 - I've not seen this before. Could you please try the following steps:

- `tns platform remove android`
- `tns platform add android`
- uninstall the app from the device/emulator
- `tns run android`

That should clear up any issues with building. If that doesn't work, you might want to start a fresh {N} app and add this plugin and see if it fails for you again. I don't think it will, this error is most likely not a direct result of this plugin. I've seen similar errors and it's not the plugin causing the issue but more of a build/config issue when adding numerous plugins/libraries. Let me know if that works for you.

**Comment by t1amat9409** [comment]
@bradmartin 

I did as mentioned on your reply.
It did work, thanks a lot...
