### ISSUE TITLE
Request to support HTML file templates too

### ISSUE THREAD

**Issue by Headcult** [bradmartin/nativescript-floatingactionbutton#21]
Excellent plugin for the much needed Floating Action Button!

How do we import/implement the plugin if I'm using a separate HTML file (from the templateURL) as I'm using Angular 2 with NativeScript in my application. I would love to use this plugin in my app but currently, I'm not able to as I'm not using any XML for my views.

**Comment by bradmartin** [comment]
I've not tried ng2 with NativeScript yet, holding out for end of beta :smile:  However, I'm pretty sure you can use this with ng2, I think some people have been doing so from the conversations on the community slack channel. You might want to drop in there and ask around to see.

**Comment by bradmartin** [comment]
@Headcult you figured it out correct? If so, go ahead and close this and list the solution for future users. Thanks.

**Comment by Headcult** [comment]
Yeah!, This is supported now. Here's are the overall steps to get this working with Angular 2:

1. Add these to your `dependencies` section in your `package.json`:

    >"nativescript-floatingactionbutton": "2.2.1",
2. Run `npm install`.
3. Add the following lines before you bootstrap (nativeScriptBootstrap) your app:

      >import {registerElement} from "nativescript-angular/element-registry";
      registerElement("FAB", () => require("nativescript-floatingactionbutton").Fab);
4. Now, you can use the `FAB` in your templateURL (HTML files) as you wish like shown below:

    >            <FAB tap="fabTap"
                     row="1"
                     icon="res://icon"
                     rippleColor="#f1f1f1"
                     class="fab-button">
            </FAB>
5. Add the following to your app.css for styling:

  >.fab-button {
    height: 70;
    margin: 15;
    background-color: #ff4081; 
    horizontal-align: right; 
    vertical-align: bottom; 
}

6. If you run into an error like this while running `tns run android`:

    >Exception in thread "main" java.lang.IllegalArgumentException: Class com.tns.internal.AppBuilderCall
back conflict: \platforms\android\build\intermediates\classes\debug and
\platforms\android\build\intermediates\classes\nativescriptcardview\
debug
      at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
      at com.telerik.metadata.Builder.build(Builder.java:41)
      at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':buildMetadata'.
Process 'command 'C:\Java\jdk1.8.0_25\bin\java.exe'' finished with non-zero exit value 1

7. then, do the following:
    >Run `gradlew clean` in the `platforms > android` folder.

8. Run `tns run android` again, it'll fix the issue and you'll see the FAB on your Angular 2 app!

**Comment by pep108** [comment]
If anyone's having a hard time getting the tap to register in the angular 2 component, just change 
`tap="fabTap"` to `(tap)="fabTap()"`

**Comment by dlucidone** [comment]
Hey, Im getting some sort of android error. I have tried gradle clean and replacing android platform too.
Any Help! Thanks!

**Comment by bradmartin** [comment]
Could you please post the error, package.json, and relevant code files?
Thanks

**Comment by dlucidone** [comment]
uninstalling and installing again solved my problem. Thanks for the reply

**Comment by chuckmitchell** [comment]
Do I add the Element registration code to `main.ts,` before the following line?

> platformNativeScriptDynamic().bootstrapModule(AppModule);

This is the code I'm talking about:
> import {registerElement} from "nativescript-angular/element-registry";
> registerElement("FAB", () => require("nativescript-floatingactionbutton").Fab);`
