### ISSUE TITLE
Problem using with RadListView

### ISSUE THREAD

**Issue by f-marquez** [bradmartin/nativescript-floatingactionbutton#23]
First of all, thank you very much for the plugin !!

After installing the plugin in an app that use the RadListView component (nativescript-telerik-ui) seems to insert a page break after each item in the RadListView even if you don't use the floating action button in this page.

If you uninstall the plugin, the RadListView looks well again.

Perhaps the problem is in the RadListView plugin and not here ...

Before installing the plugin:
![screenshot-5](https://cloud.githubusercontent.com/assets/18644204/14770175/4402b204-0a6b-11e6-94cb-34cdbcec33a6.png)

After installing the plugin:
![screenshot-4](https://cloud.githubusercontent.com/assets/18644204/14770176/440795ee-0a6b-11e6-8692-1c12d3b74766.png)

Thanks a lot in advance!!

**Comment by sitefinitysteve** [comment]
I am experiencing this on the radlistview with no fab...  Don't think it's related. However that being said telerik can't seem to replicate... Would you be able to provide a sample project replicating it?

**Comment by f-marquez** [comment]
I agree with you, the issue can be in other part of the code but, in my case, it only occurs when I install the fab plugin.

radlistview working right -> [my-app.zip](https://github.com/bradmartin/nativescript-floatingactionbutton/files/235007/my-app.zip)
![screenshot from 2016-04-25 18 55 22](https://cloud.githubusercontent.com/assets/18644204/14791995/95fee066-0b18-11e6-9031-9053b1e61777.png)

radlistview + fab -> [my-appFAB.zip](https://github.com/bradmartin/nativescript-floatingactionbutton/files/235014/my-appFAB.zip)
![screenshot from 2016-04-25 18 55 45](https://cloud.githubusercontent.com/assets/18644204/14792050/c65e8360-0b18-11e6-92c9-07760158f973.png)

**Comment by sitefinitysteve** [comment]
You arent specifying row="0" on the RadListView, try that

**Comment by f-marquez** [comment]
Tested with same result.

`<GridLayout rows="*">
    <lv:RadListView id="list-view" items="{{ items }}" row="0">
      <lv:RadListView.listViewLayout>`


![screenshot from 2016-04-25 19 14 40](https://cloud.githubusercontent.com/assets/18644204/14792357/2a48413a-0b1a-11e6-8b33-5f6b1a2f30d8.png)

**Comment by bradmartin** [comment]
Testing a few things out, let you guys know what I find.

**Comment by bradmartin** [comment]
Okay, appears to be an issue with the RadListView. I am experiencing the issue with no FAB plugin on Android 6.0 - Droid Turbo 2. Checking a few other API levels now.

I've tried placing a `Placeholder` on the listview with an android button and same issue, with the plugin installed, without the plugin. Same result no matter what.

**Comment by bradmartin** [comment]
K. Not API specific, Think the real issue is when the Design library is added to the project. I removed the platforms, added back, built the project and using a placeholder works fine. 

### No Design Library w/ `Placeholder` using android.widget.Button
![nodesignlib](https://cloud.githubusercontent.com/assets/6006148/14794899/adc690e0-0aeb-11e6-92b0-6e33752b0ba2.PNG)

### Design Library w/ `Placeholder` using android.widget.Button
![withdesign](https://cloud.githubusercontent.com/assets/6006148/14795165/d01f83d0-0aec-11e6-9fc8-66c14a102e98.PNG)

**Comment by bradmartin** [comment]
![withdesign](https://cloud.githubusercontent.com/assets/6006148/14795190/f39bc792-0aec-11e6-91c1-a639907975d4.gif)

**Comment by f-marquez** [comment]
This solution `No Design Library w/  Placeholder  using android.widget.Button` could be nice for me.
![screenshot from 2016-04-26 08 02 42](https://cloud.githubusercontent.com/assets/18644204/14808473/b4263c70-0b85-11e6-8b94-969e6e250d4b.png)

Thank you very much for your support !!

**Comment by bradmartin** [comment]
It's an okay workaround but when the design lib is included it breaks the
listview and the design lib has more components/features than just the FAB.
Hopefully they find a fix soon :)

**Comment by f-marquez** [comment]
You are right, this morning I got the same issue doing some tests with the nativescript-photoviewer plugin.
