### ISSUE TITLE
iOS Build Error on Telerik AppBuilder

### ISSUE THREAD

**Issue by tsaboin** [bradmartin/nativescript-floatingactionbutton#24]
Getting the following error on the Telerik AppBuilder when trying to build a project.

Error: Cannot build project because module nativescript-floatingactionbutton contains insecure code. Remove the module and try again.

**Comment by bradmartin** [comment]
Hi, thanks for reporting. I'm unfamiliar with the AppBuilder, I only use
the CLI. Is there anymore information from the error? A line number or
file? Without that I don't think I'll be able to help you out any. The iOS
version does use a cocoapod for the component. Which I'm not sure how
AppBuilder handles cocoapods. That might be part of the issue. Hopefully
you have some more information for the error.

Thanks :smile:

**Comment by tsaboin** [comment]
Thanks @bradmartin,

Here is my entire log:
[2016-05-08 20:06:24.402] Log (Info,None): Project "test.tmp.proj" (default targets):
	ios Build Tooling revision 2016.05.03.3r
	Warning: npm
	Warning: WARN
	Warning: package.json
	Warning: @ No description
	Warning: npm
	Warning: WARN
	Warning: package.json
	Warning: @ No repository field.
	Warning: npm
	Warning: WARN
	Warning: package.json @ No README data
	Warning: npm
	Warning: WARN
	Warning: package.json
	Warning: @ No license field.
	Error: Cannot build project because module nativescript-floatingactionbutton contains insecure code. Remove the module and try again.
	Error: 'Build failed with error code 2'
Done building project "test.tmp.proj" -- FAILED.

Hopefully it makes sense to you.

**Comment by bradmartin** [comment]
Just found out it's a security measure by  AppBuilder. First time I've had
anyone report the issue. Plugin authors have to be verified if the plugin
uses a cocoapod. So once I'm added my plugins with pods should all work
with AppBuilder.

**Comment by tsaboin** [comment]
Yea, I read that somewhere too and the author is required to submit the app for verification. Good plugin by the way. Saves a lot of time.

**Comment by bradmartin** [comment]
Okay, I heard back from the Telerik AppBuilder team. They actually review plugin author's github account to make sure they are legit and not doing anything shady to compromise the integrity of AppBuilder. I've been white listed and when the next release of AppBuilder happens the plugin shouldn't throw this error anymore.

**Comment by tsaboin** [comment]
Good job @bradmartin
