### ISSUE TITLE
How can I do "showOnSwipeOfView"

### ISSUE THREAD

**Issue by ryc16** [bradmartin/nativescript-floatingactionbutton#28]
Hi,

I saw there are an attribute "hideOnSwipeOfView". From your demo where you use ListView for hideOnSwipeOfView. When scroll down, the FAB hide; and when scroll up, the FAB show. I would like to do other way around - show when scroll down and hide when scroll up (basically on top). How to do this way?

Thanks

**Comment by bradmartin** [comment]
@ryc16 - instead of using the built in `hideOnSwipeOfView` attribute you would add a `gesture` to some layout on your page and reverse the animations. We use the NS animation API to do those effects. So it's nothing secret :wink: If you need more info let me know.

**Comment by ryc16** [comment]
@bradmartin, understood. looked at your plugin and found it is in fab-common.js. Was hoping it supports out of box. Probably will change your plugin but it is nice if it is included into your plugin.

**Comment by sitefinitysteve** [comment]
You shouldn't change the plugin at all, you should just implement the swipe on your code. However i think its a valid request to consider... I just don't have time today :)
