### ISSUE TITLE
Change icon size

### ISSUE THREAD

**Issue by eurica-larazo** [bradmartin/nativescript-floatingactionbutton#29]
Is it possible to change the icon size of the floating button? Let say i wanna have a floating button but it covers all of the circle button. Or is there some kind of work around that I can do?

**Comment by bradmartin** [comment]
Sizing the icon isn't possible from what I know of the native android widget. You could size the fab to a mini fab but that's not adjusting the icon in the fab. I don't see any methods allowing you to size it directly with the fab, it's likely possible you could get lower to the image view that's extended from with the FAB to control some sizing but that's not something I've seen or have any interest or time in providing out of the box with this plugin. I'll accept a PR if someone wants to add that in. Hope that helps explain things some.

**Comment by sitefinitysteve** [comment]
You could do it on the iOS side by just maybe digging into the .ios.subviews, finding the image and just making it larger
