### ISSUE TITLE
[Android] Missing click noise

### ISSUE THREAD

**Issue by roblav96** [bradmartin/nativescript-floatingactionbutton#30]
The only way I can get the click noise to work on android is if I add a `setTimeout` method before calling `topmost().navigate`:
```typescript
export function gotoAddConvo(args: EventData) {
	setTimeout(function() {
		topmost().navigate('listpage/listpage')
	}, 100)
}
```
Any idea why? Just curious 👼

**Comment by bradmartin** [comment]
Not really sure what you're referring to. There is no noise by default on the fab that I'm aware of. I've tried several apps with fab (inbox, twitter) and there's no noise on the fab tap. So do you have a sample app on the play store so I can see it in action. Is it the haptic feedback that you might be referring to?

**Comment by roblav96** [comment]
Yes it's the haptic feedback click/pop noise. It's in every app I've ever used on my phone. It's a sound; not a vibrate.

**Comment by roblav96** [comment]
Here's a quick screencast video. Turn up your volume, it's kinda faint.

https://vid.me/Lyu9

**Comment by roblav96** [comment]
Here's a quick screencast video. Turn up your volume, it's kinda faint.

https://vid.me/Lyu9

**Comment by bradmartin** [comment]
I've never heard that LOL. I don't have any app with a fab that does that,
never knew. Well to answer your question, no clue about it cause I've never
heard it

**Comment by bradmartin** [comment]
In that video was it also providing feedback on all buttons? If so I'm thinking this is device specific or something. I have haptic feedback on some buttons on my droid turbo 2 but none of my apps do it that I know of. I'm going to play around today and see if there's something I'm missing in twitter, messenger, Shazam, and inbox. They all use fab and material buttons and I just can't recall any feedback on button taps on my phone

**Comment by sitefinitysteve** [comment]
Hmm yeah i just tested on my S6 in Gmail and Twitter full volume, no haptic or sound. 

Think it is a thing in android though...  setSoundEffectsEnabled?

**Comment by roblav96** [comment]
@bradmartin @sitefinitysteve This is an accessibility feature in the android settings.
![Other Sounds](https://s21.postimg.org/u46o8ttaf/Screenshot_20160901_121245.png)

**Comment by bradmartin** [comment]
Ahh so yea device setting. If you want to make a PR to enable the sound via an optional parameter (since you mentioned timeout, don't want that the default).

**Comment by roblav96** [comment]
@bradmartin Sure I'll give it a shot.

**Comment by bradmartin** [comment]
Nothing changed and I tested today (after turning the setting to ON) and the sound is there. Same as Twitter and Inbox apps FAB button sound (and all other taps it seems).

**Comment by roblav96** [comment]
Yes everything is working properly. Thank you!
