### ISSUE TITLE
[iOS] UI Builder Error

### ISSUE THREAD

**Issue by huehnerhose** [bradmartin/nativescript-floatingactionbutton#31]
Hi,

I am not able to use floatingactionbutton on ios. Everytime I the page with FAB:fab renders i get a segmentation fault. Android works fine. 

To be sure the errors isn't between keyboard and chair, I made a new project with your sample code. Android works just fine, iOS output is:

    ** BUILD SUCCEEDED **

    Project successfully built
    Successfully deployed on device with identifier 'FFA9A3FA-8F47-4EF0-B8F1-CCAC8B5C2B28'.
    Sep  1 18:26:02 Munin backboardd[788]: SecTaskCopyDebugDescription: test[16405]
    Sep  1 18:26:02 Munin backboardd[788]: SecTaskCopyDebugDescription: test[16405]
    Sep  1 18:26:02 Munin backboardd[788]: SecTaskCopyDebugDescription: test[16405]
    Sep  1 18:26:02 Munin backboardd[788]: SecTaskCopyDebugDescription: test[16405]
    Sep  1 18:26:02 Munin backboardd[788]: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
    Sep  1 18:26:02 Munin backboardd[788]: SecTaskCopyDebugDescription: test[16405]
    Sep  1 18:26:02 Munin test[16405]: assertion failed: 15G31 13E230: libxpc.dylib + 57882 [66C28065-C9DB-3C8E-926F-5A40210A6D1B]: 0x7d
    Sep  1 18:26:02 --- last message repeated 1 time ---
    Sep  1 18:26:02 Munin test[16405]: 1   0x109130709 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
    Sep  1 18:26:02 Munin test[16405]: 2   0x10979b01e ffi_closure_unix64_inner
    Sep  1 18:26:02 Munin test[16405]: 3   0x10979b9d2 ffi_closure_unix64
    Sep  1 18:26:02 Munin test[16405]: 4   0x10a37dcd3 -[UIViewController view]
    Sep  1 18:26:02 Munin test[16405]: 5   0x10a253fb4 -[UIWindow addRootViewControllerViewIfPossible]
    Sep  1 18:26:02 Munin test[16405]: 6   0x10a25469d -[UIWindow _setHidden:forced:]
    Sep  1 18:26:02 Munin test[16405]: 7   0x10a266180 -[UIWindow makeKeyAndVisible]
    Sep  1 18:26:02 Munin test[16405]: 8   0x10979b82d ffi_call_unix64
    Sep  1 18:26:02 Munin test[16405]: 9   0x11cfba250
    Sep  1 18:26:02 Munin test[16405]: file:///app/tns_modules/ui/builder/builder.js:162:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:12:13
             ↳Module '/Users/huehnerhose/Library/Developer/CoreSimulator/Devices/FFA9A3FA-8F47-4EF0-B8F1-CCAC8B5C2B28/data/Containers/Bundle/Application/495B675C-5892-4F65-B0F3-C7A19C3A270D/test.app/app/tns_modules/nativescript-floatingactionbutton' not found for element 'nativescript-floatingactionbutton:Fab'.
               ↳Can't find variable: MNFloatingActionButton
    Sep  1 18:26:02 Munin com.apple.CoreSimulator.SimDevice.FFA9A3FA-8F47-4EF0-B8F1-CCAC8B5C2B28.launchd_sim[771] (UIKitApplication:org.nativescript.test[0x1d0e][16405]): Service exited due to signal: Segmentation fault: 11

Using: tns version 2.2.1

**Comment by bradmartin** [comment]
The error `Can't find variable: MNFloatingActionButton` stands out.

Did you do a rebuild of your app after adding the plugin? If not read this: https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/ and let me know if it continues.

**Comment by huehnerhose** [comment]
Well I started a fresh project to isolate my error. But I also tried what's said in the link. No change.

**Comment by sitefinitysteve** [comment]
I would maybe say it's a cocoapod issue, what version are you running, and did you sudo it?

**Comment by huehnerhose** [comment]
I don't really know :( Sorry. I followed this guide http://docs.nativescript.org/start/ns-setup-os-x

Maybe this helps?
```
tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.2.1           │ 2.2.1          │ Up to date  │
│ tns-core-modules │ 2.2.1           │ 2.2.1          │ Up to date  │
│ tns-android      │ 2.2.0           │ 2.2.0          │ Up to date  │
│ tns-ios          │ 2.2.1           │ 2.2.1          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘

pod --version
1.0.1
```

**Comment by huehnerhose** [comment]
I'm just curious whether you can tell me when/how this can be fixed or if this is a bigger issue? Or what I can do to help to narrow down the issue?

**Comment by sitefinitysteve** [comment]
Can you try cocoapods 0.39?

**Comment by huehnerhose** [comment]
Sorry... I am not familiar with this stuff :/
What I tried:
```
sudo gem install cocoapods -v 0.39
tns platform remove ios
tns platform add ios
tns doctor
tns build ios
````
I uninstalled the app from the device and did `tns run ios`
Same error.

If I have to do something else to change the used cocoapods version can you please give me the instructions?

Thanks

**Comment by bradmartin** [comment]
I don't do much iOS either but I think he means local cocoapods. Google around and see about installing that version on your mac.

**Comment by bradmartin** [comment]
Did you ever get it to build? This issue does seem like a cocoapod issue on your system. I've seen something similar on other plugins and some said switching cocoapods fixed it.

**Comment by bradmartin** [comment]
I just tested the demo app and everything is still working on both android and iOS for me.

**Comment by bradmartin** [comment]
To check your version of cocoapods see here and the command below
http://stackoverflow.com/a/31177514/1893557

- `gem which cocoapods`
