### ISSUE TITLE
Unable to find a specification for `MNFloatingActionButton (~> 0.1.5)`

### ISSUE THREAD

**Issue by chanmyaethu-mn** [bradmartin/nativescript-floatingactionbutton#33]
I use this in native script. When I build project, I found the error which is followed.

[!] Unable to find a specification for `MNFloatingActionButton (~> 0.1.5)`
Processing node_modules failed. Error: Command pod failed with exit code 1

**Comment by bradmartin** [comment]
I'm checking on this. That seems to be the version specified on cocoapods. I recently updated it.

For now you could go into the node_modules/nativescript-floatingactionbutton/platforms/ios/PodFile file and change the line to the old version:

```
pod 'MNFloatingActionButton', '~> 0.1'

```

which should resolve during the build. If I can't get any help on the iOS updated pod issue I'll roll back to the working version above and publish an update to the package.

**Comment by NathanWalker** [comment]
You likely need to pin the pod to the old version in meantime:
```
pod 'MNFloatingActionButton', '0.1'
```

**Comment by NathanWalker** [comment]
@chanmyaethu-mn Your error suggests an incompatible Cocoapods version though, do this:
```
pod --version
```
What do you have?
Then also do this:
```
sudo gem list cocoapods
```
Please let us know your output.

Ideally you need this output:
```
cocoapods (0.39.0)
cocoapods-core (0.39.0)
```
If you have a higher version, you may want to uninstall all cocoapod listings and just instal `0.39.0` using this guide:
http://diego.org/2015/09/24/downgrading-cocoapods/

**Comment by chanmyaethu-mn** [comment]
Thank bradmartin and NathanWalker for your answering.
I have tested like this which is your mentioned.

I solved the problem by downgrading cocoapods 1.0.1 to 0.39.0.

But I face the broblem UI build error which is shown below

> file:///app/tns_modules/ui/builder/builder.js:162:56: JS ERROR Error: Building UI from XML. @file:///app/views/login/login-page.xml:41:13
> 	 ↳Module '/Users/techfunmmr/Library/Developer/CoreSimulator/Devices/9385A15F-7052-4E6F-AB26-17972205750D/data/Containers/Bundle/Application/F274E59A-0E78-42DC-9CAA-293E18C58E83/typescripthelloworld.app/app/tns_modules/nativescript-floatingactionbutton' not found for element 'nativescript-floatingactionbutton:Fab'.
> 	   ↳Can't find variable: MNFloatingActionButton
> Oct  5 11:37:22 Techfunmmrs-Mac-mini com.apple.CoreSimulator.SimDevice.9385A15F-7052-4E6F-AB26-17972205750D.launchd_sim[1030] (UIKitApplication:org.nativescript.typescripthelloworld[0x7803][1389]): Service exited due to Segmentation fault: 11

**Comment by dondragon2** [comment]
after making the changes i am getting these errors
```
[!] Unable to satisfy the following requirements:

- `MNFloatingActionButton (~> 0.1.5)` required by `Podfile`
- `MNFloatingActionButton (~> 0.1)` required by `Podfile`
- `MNFloatingActionButton (= 0.1)` required by `Podfile`
- `MNFloatingActionButton (= 0.1.5)` required by `Podfile.lock`

Specs satisfying the `MNFloatingActionButton (~> 0.1.5), MNFloatingActionButton (~> 0.1), MNFloatingActionButton (= 0.1), MNFloatingActionButton (= 0.1.5)` dependency were found, but they required a higher minimum deployment target.
Processing node_modules failed. Error: Command sandbox-pod failed with exit code 1 Error output: 
 
[!] There are duplicate dependencies on `MNFloatingActionButton` in `Podfile`:

- MNFloatingActionButton (~> 0.1.5)
- MNFloatingActionButton (~> 0.1)
- MNFloatingActionButton (= 0.1)
```

**Comment by tscislo** [comment]
Hi,

Unfortunately with version 3.0.0 I still get this issue.
Is there any permanent solution, not a workaround?

Thx!
