### ISSUE TITLE
Feature Request: Speed Dial

### ISSUE THREAD

**Issue by leocaseiro** [bradmartin/nativescript-floatingactionbutton#35]
Hi @bradmartin, thank you so much for this awesome plugin.

I was wondering, how complex would be to implement a speed dial for this floating action button?

I know this one for ios is pretty cool because come also with labels: https://github.com/kciter/KCFloatingActionButton

**Comment by bradmartin** [comment]
Don't need a pod or anything for it. Did it long ago.
https://youtu.be/3n8cuJZmOvw the snippet should be on the NativeScript
snacks website. I might have blogged it also. Don't quite remember. Hope
that helps some

**Comment by bradmartin** [comment]
Adding to that. To add labels wouldn't be too difficult either using that snippet in the snack as a starting point. I've meant to add that snippet to the readme.

**Comment by leocaseiro** [comment]
Wow! That's awesome!

@Domgaud sent me the snipped [from nativescriptsnacks](http://www.nativescriptsnacks.com/snippets/2016/04/22/fab-button.html);

Thanks @bradmartin
