### ISSUE TITLE
ORIGINAL EXCEPTION: Can't find variable: MNFloatingActionButton

### ISSUE THREAD

**Issue by gnjuguna** [bradmartin/nativescript-floatingactionbutton#39]
Hi, after updating Nativescript to the latest version, I'm getting the error below when building for IOS. Android not affected.

CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3006:36: ORIGINAL EXCEPTION: Can't find variable: MNFloatingActionButton
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3009:36: ORIGINAL STACKTRACE:
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3010:36: FloatingActionButton@file:///app/tns_modules/nativescript-floatingactionbutton/fab.js:20:44
	createAndAttach@file:///app/tns_modules/nativescript-angular/view-util.js:96:33
	createView@file:///app/tns_modules/nativescript-angular/view-util.js:110:40
	createElement@file:///app/tns_modules/nativescript-angular/renderer.js:198:40
	createRenderElement@file:///app/tns_modules/@angular/core/bundles/core.umd.js:5450:40
	createInternal
	create@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9370:52
	createEmbeddedView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:7240:24
	createEmbeddedView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:4847:57
	ngOnInit@file:///app/tns_modules/nativescript-angular/directives/tab-view.js:80:60
	detectChangesInInputProps
	detectChangesInternal
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9305:39
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9410:52
	detectViewChildrenChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9331:36
	detectChangesInternal
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9305:39
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9410:52
	detectContentChildrenChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9323:36
	detectChangesInternal
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9305:39
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9410:52
	detectContentChildrenChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9323:36
	detectChangesInternal
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9305:39
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9410:52
	detectViewChildrenChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9331:36
	detectChangesInternal
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9305:39
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9410:52
	detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:7398:37
	forEach@[native code]
	tick@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6819:49
	file:///app/tns_modules/@angular/core/bundles/core.umd.js:6760:113
	invoke@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:190:33
	onInvoke@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6206:47
	invoke@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:189:42
	run@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:83:49
	next@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6760:88
	file:///app/tns_modules/@angular/core/bundles/core.umd.js:5952:60
	__tryOrUnsub@file:///app/tns_modules/rxjs/Subscriber.js:223:20
	next@file:///app/tns_modules/rxjs/Subscriber.js:172:34
	_next@file:///app/tns_modules/rxjs/Subscriber.js:125:30
	next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
	next@file:///app/tns_modules/rxjs/Subject.js:55:29
	emit@file:///app/tns_modules/@angular/core/bundles/core.umd.js:5944:84
	checkStable@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6174:48
	setHasMicrotask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6245:29
	onHasTask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6218:50
	hasTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:249:64
	_updateTaskCount@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:266:33
	invokeTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:227:42
	runTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:123:57
	drainMicroTaskQueue@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:355:42
	promiseReactionJob@[native code]
	UIApplicationMain@[native code]
	start@file:///app/tns_modules/application/application.js:251:30
	bootstrapApp@file:///app/tns_modules/nativescript-angular/platform.js:60:26
	bootstrapModule@file:///app/tns_modules/nativescript-angular/platform.js:53:26
	anonymous@file:///app/main.js:5:57
	evaluate@[native code]
	moduleEvaluation@[native code]
	[native code]
	promiseReactionJob@[native code]
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3013:36: ERROR CONTEXT:

**Comment by bradmartin** [comment]
I believe this might be a cocoa pods issue. I can check later. Make sure
you're using 1.0

**Comment by gnjuguna** [comment]
Downgrading cocoapods from 1.1.1 to 1.0.1 seems to have solved the problem. 

Thanks for the tip and the awesome plugin.

**Comment by Pinny3** [comment]
@gnjuguna 

I think it's not a good idea to migrate down to CocoaPods 1.0.1, since we are running a build-server with many other projects on it and they rely on the lastest version CocoaPods. 

So, is there any other way how this issue can be solved? Maybe this is already solved?

**Comment by bradmartin** [comment]
Should be fine now. At the time cocoapods had issues importing correctly, not sure what the issue was exactly. However I've not ran into this myself in over a year. So all should be okay now :)
