### ISSUE TITLE
Floating Textfield + button bottom of the view

### ISSUE THREAD

**Issue by raosrinivas1983** [bradmartin/nativescript-floatingactionbutton#41]
Hi, 

I'm working on a chat application in nativescript,  i'm unable to display textfield + button bottom of the view. Have tried different layout mechanisms but no luck. If you have any idea how can i display below to the listview. Below is my existing code, its working perfectly in android emulator but text field and button is not visible in actual phone.  Thanks in advance.

    <GridLayout>
        <GridLayout rows="auto, *, auto, auto" class="nsChatView-view">
            <ListView 
                #messageList
                row="1"
                class="nsChatView-messageList">
                <template let-item="item">
                <GridLayout rows="auto" columns="auto,*,auto"
                    [class]="item.isRight ? 'nsChatView-item-right' : 'nsChatView-item-left'">
                        <Image row="0" col="item.isRight ? '2' : '0'"         
                            class="nsChatView-avatar" 
                            verticalAlignment="top"   
                            [src]="item.image"    
                            [visibility]="item.image ? 'visible' : 'collapsed'" ></Image>
                            <StackLayout row="0" col="1" class="nsChatView-message">
                                    <Border class="nsChatView-messageArea">
                                        <StackLayout class="nsChatView-content" verticalAlignment="middle" 
                                            [horizontalAlignment]="item.isRight ? 'right' : 'left'">
                                            <Label class="nsChatView-date" [horizontalAlignment]="item.isRight ? 'right' : 'left'" 
                                                [text]="item.date" 
                                                [visibility]="item.date ? 'visible' : 'collapsed'" ></Label>
                                            <Label class="nsChatView-messageText" 
                                                [horizontalAlignment]="item.isRight ? 'right' : 'left'"
                                                [text]="item.message" textWrap="true"></Label>
                                        </StackLayout>
                                    </Border>
                            </StackLayout>
                            <Border row="0" [col]="item.isRight ? '0' : '2'" class="nsChatView-separator" ></Border>
                    </GridLayout>   
                </template>
            </ListView>
            <AbsoluteLayout row="1" class="nsChatView-sendMessageArea">
                <GridLayout width="99%" height="40" row="1" class="nsChatView-sendMessageArea" columns="*, auto" verticalAlignment="top">
                        <TextField row="0" col="0" #msgTextField  class="nsChatView-messageField" (returnPress)="onSendTap()" [hint]="typeMessageHint"></TextField>
                        <Button row="0" col="1" class="nsChatView-sendMessageButton" (tap)="onSendTap()" text="Send"></Button>
                </GridLayout>
            </AbsoluteLayout>  
        </GridLayout>
         
    </GridLayout>

**Comment by bradmartin** [comment]
Do you have some mock up of the screen I can see? I have a general sense of what you want, but seeing it makes it much easier 👍

**Comment by raosrinivas1983** [comment]
Hi Martin,

Thanks for the quick reply. Attached the screens shots for both horizontal and vertical orientation. You can observe in vertical orientation text field and buttons are not visible and rendered outside the visible view.

![screenshot_20161209-092356](https://cloud.githubusercontent.com/assets/17030089/21037189/d09a50e8-bdf1-11e6-9322-318ea7c9b30b.png)
![screenshot_20161209-092409](https://cloud.githubusercontent.com/assets/17030089/21037193/d4d3e8f4-bdf1-11e6-8119-65b78d9026ac.png)

**Comment by raosrinivas1983** [comment]
HI

Forgot to mention, the same code works in the older Android(4.4.2) and not the latest android

**Comment by bradmartin** [comment]
Without knowing more of the code for the project, mainly styles, could you try setting `height="100%"` on the main parent `GridLayout` and see what happens.

**Comment by raosrinivas1983** [comment]
Below is the parent control layout. Have tried 100% but no use then i gave 80%,  its displayed as below,

conversations-common.txt - styles
conversations.html.txt - parent element layout

![screenshot_20161209-101312](https://cloud.githubusercontent.com/assets/17030089/21038015/52a40402-bdf8-11e6-9b83-3f3d0e1dd1e2.png)


[conversations-common.txt](https://github.com/bradmartin/nativescript-floatingactionbutton/files/641254/conversations-common.txt)

[conversations.html.txt](https://github.com/bradmartin/nativescript-floatingactionbutton/files/641256/conversations.html.txt)

**Comment by bradmartin** [comment]
Seems strange, I don't have much time to test and debug this specific layout question. Have you joined the slack channel for NS? If not, that's a great place to get help with layout type questions. Many helpful and knowledgeable devs to help you out. You can sign up on the nativescript.org website
