### ISSUE TITLE
Throws an exception on Android 4.4

### ISSUE THREAD

**Issue by erkanarslan** [bradmartin/nativescript-floatingactionbutton#42]
![screenshot from 2016-12-15 04 03 20](https://cloud.githubusercontent.com/assets/11949947/21207884/79a7d39c-c273-11e6-9e9e-bf05c9b999b0.png)

**Comment by bradmartin** [comment]
Can you make sure all your android libraries are updated locally on your
machine? If updating and rebuilding doesn't resolve, can you post your
android manifest located in App_Resources/Android/

**Comment by erkanarslan** [comment]
The problem is nativescript cli do not correctly update an installed app on an emulator. I have uninstalled the application from AVD before running tns emulator and it works correctly.
