### ISSUE TITLE
Element for FAB already registered

### ISSUE THREAD

**Issue by shaikhspear16** [bradmartin/nativescript-floatingactionbutton#49]
Nativescript + Angular:

What is the best place to register FAB?

`registerElement("Fab", () => require("nativescript-floatingactionbutton").Fab);`

in AppModule, AppComponent, ChildComponents gives an error "Element for FAB already registered".

**Comment by Adam95** [comment]
Had the same problem. Then I placed it in my top-level app component above the class definition and it works fine now.
```
import {registerElement} from 'nativescript-angular/element-registry';

registerElement('Fab', () => require('nativescript-floatingactionbutton').Fab);

@Component({
  selector: "ns-app",
  templateUrl: "app.template.html"
})
export class AppComponent implements OnInit {
...
}
```

**Comment by bradmartin** [comment]
Thanks @adam95 for the info.

**Comment by jafsparrow** [comment]
Hi.. I am getting the same error.
I tried adding those two line in AppComponent.ts.. same error.
pretty much tried with other components too.!!
any other solution..

import {registerElement} from 'nativescript-angular/element-registry';

registerElement('Fab', () => require('nativescript-floatingactionbutton').Fab);

@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})

**Comment by bradmartin** [comment]
I do this in app.component

``` typescript
import { Fab } from "nativescript-floatingactionbutton";
import { registerElement } from "nativescript-angular/element-registry";
registerElement("Fab", () => Fab);
```

and have no issues, hope that helps.

**Comment by jafsparrow** [comment]
Tried this .. same error.
If I don't add these two line, I can see floating action. but a stretched version of it.
![image](https://user-images.githubusercontent.com/20259431/30398924-b803a3e8-98ef-11e7-803a-1974abd8e069.png)


I will try to add FAB in a brand new sample project and try..

**Comment by bradmartin** [comment]
If it's stretched then you likely don't have a `width` set on it for the styler to apply.
