### ISSUE TITLE
Nativescript versions intended?

### ISSUE THREAD

**Issue by lrsaturnino** [bradmartin/nativescript-floatingactionbutton#5]
Hi, which {N} version this plugin is intended? 

On AppBuilder from Telerik uses {N} 1.4 and it doesn't work. App crashes as soon as I call a page with a FAB button. 

When using {N} 1.5 on my local files it seems to work fine. 

Not sure if its {N} version, but that's an indication.

Also, it's strange that in my local files, nativescript-floatingactionbutton installation doesn't add any dependencies on package.json, but it works fine.

**Comment by bradmartin** [comment]
I'm not too familiar with appbuilder, I think they have to be whitelisted
by the NativeScript team before it will work on appbuilder. As for {N}
version, NativeScript has little to nothing to do with the plugin as long
as the module is found and you have the android library installed on your
machine it will work correctly.

You might want to look at AppBuilders plugin documentation and see if that
provides any insight.

**Comment by lrsaturnino** [comment]
Hi Brad, I took a look at AppBuilder docs and found that they are currently supporting {N} 1.5, I just upgraded my project (had little issues), but good new is that nativescript-gloatingactionbutton is working fine!

**Comment by bradmartin** [comment]
Good deal. I thought they had to white list plugins but maybe they've fixed
that since earlier days.

**Comment by bradmartin** [comment]
@lrsaturnino - I'll close this now. Any other issues let me know :+1:
