### ISSUE TITLE
Update for 3.0 breaking changes - [nativescript 3.0] ui/core/proxy  missing 

### ISSUE THREAD

**Issue by dgomezs** [bradmartin/nativescript-floatingactionbutton#50]
The upcoming release of nativescript has remove the ui/core/proxy module. Will the plugin be compatible with 3.0? any estimates on when that could happen?

thank you very much in advanced.

**Comment by bradmartin** [comment]
No estimate right now. Little time personally to update. It will definitely support 3.0 breaking changes though, just can't give a good time line as of now. I believe some popular UI plugins will receive some attention from the NS core team soon to update. So keep an eye on forks from one of the core members. As always PRs welcome to make the updates 😄

**Comment by bradmartin** [comment]
Try out the 3.0.0 version of the plugin - just published.
