### ISSUE TITLE
Exit from google maps intent using FAB

### ISSUE THREAD

**Issue by lutoqui** [bradmartin/nativescript-floatingactionbutton#54]
I am implementing custom turn-by-turn navigation in my NativeScript application. To achieve this, I have started an activity using an android.content.Intent uses android.content.Intent.ACTION_VIEW as action and "google.navigation:q" as Uri string. The google maps navigation page is successfully loaded in my app.
Is there any possibility to place FAB (exit button) or other similar view/widget on top of this new intent?.

**Comment by bradmartin** [comment]
You possibly could if the intent can be overlayed. I've never done this, typically an intent starts a new activity which is more or less a new application. So I don't think this is possible without some heavy android knowledge on managing the window and activities.
