### ISSUE TITLE
Error when navigating to the page contains FAB NativeScript 3.x.x

### ISSUE THREAD

**Issue by OPADA-Eng** [bradmartin/nativescript-floatingactionbutton#55]
Hi, 
After I update my project to NS 3 I faced a crush when I navigate to the page contains FAB on ios 
what I did :
`tns create test-fab --template typescript`
`tns platform add ios`
`tns plugin add nativescript-floatingactionbutton`
`tns run ios` (on emulator)

then I get this crush error: 

> file:///app/tns_modules/tns-core-modules/ui/builder/builder.js:195:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:12:13
	 > Module '/Users/codeobia/Library/Developer/CoreSimulator/Devices/2792A572-93F5-493C-BCE2-C2DCEB7AC2F1/data/Containers/Bundle/Application/E5FC442D-A3E8-4FAD-8198-5D24528F34C3/testfab.app/app/tns_modules/nativescript-floatingactionbutton' not found for element 'nativescript-floatingactionbutton:Fab'.
	   > Can't find variable: MNFloatingActionButtonJul 16 09:14:22 Codes-MacBook-Pro com.apple.CoreSimulator.SimDevice.2792A572-93F5-493C-BCE2-C2DCEB7AC2F1.launchd_sim[21552] (UIKitApplication:org.nativescript.testfab[0xd57e][21574][29510]): Service exited due to Segmentation fault: 11
9:14:23 AM - Compilation complete. Watching for file changes.

Any help ?

**Comment by bradmartin** [comment]
Can you share your xml? I believe you forgot to add the `xmlns` to the page component so the builder doesn't know where to locate the correct file to build the FAB. That should help here. Please let me know, thanks.

**Comment by OPADA-Eng** [comment]
This is the hole project
[test-fab.zip](https://github.com/bradmartin/nativescript-floatingactionbutton/files/1162020/test-fab.zip)

**Comment by bismert** [comment]
I am faced with similar issue

**Comment by bradmartin** [comment]
Can you paste the error output being throw? I don't have time to run demos
right now and seeing your markup, package.json, and the error is typically
sufficient to find what is wrong. Thanks.

**Comment by OPADA-Eng** [comment]
The Error output in the first comment !

**Comment by bradmartin** [comment]
Overlooked it. Thanks. So yes I'm not gonna download a zip can you just paste the relevant code files here in markdown. Either you don't have the xmlns added to the page for the parser to know what the Fab is or the pod didn't install correctly for iOS. I just added this to a project yesterday and it works fine on Android and iOS so definitely we can find what's causing the issue for you. Thanks.

**Comment by OPADA-Eng** [comment]
`<Page xmlns="http://schemas.nativescript.org/tns.xsd"
  xmlns:drawer="nativescript-telerik-ui/sidedrawer"
  xmlns:sidedrawer="/sidedrawer"
  xmlns:actionBar="/actionBar"
  xmlns:FAB="nativescript-floatingactionbutton"
  xmlns:IC="nativescript-web-image-cache"
      navigatedTo="navigatedTo"
      navigatingTo="navigatingTo"
  navigatingFrom="navigatingFrom"
      loaded="pageLoaded">
        <FAB:fab tap="{{fabTap}}"
                     row="1"
                     icon="~/images/ic_add_white.png"
                     rippleColor="#5f7358"
                     class="fab-button" />
</Page>`

**Comment by bradmartin** [comment]
All seems okay. I have the FAB working fine in 3.1 and 3.2 plain NS apps. It works fine also with 3.2 w/ Angular. I've just updated a couple of apps today and have not encountered any issue. 
If you're still having this error please let me know.
