### ISSUE TITLE
Pods are not installed on a case sensitive file system

### ISSUE THREAD

**Issue by simonox** [bradmartin/nativescript-floatingactionbutton#56]
Platform: iOS
Error: Pods are not installed. This will cause a runtime exception on first "usage".
Version: 3.0.0
 
FAB is not installed on a case sensitive file system.

```pod install```is looking for a file named ```Podfile```.

The file in this plugin is named ```PodFile```. So it is ignored if your file system is case sensitive.

![screen shot 2017-07-19 at 17 42 20](https://user-images.githubusercontent.com/117064/28376551-ae5faefc-6caa-11e7-9709-86274f8d5c5c.png)

If I rename this file, the pods are installed.

**Comment by bradmartin** [comment]
3.0.1 published with the case fixed
