### ISSUE TITLE
FAB on Android 5.1 does not display properly

### ISSUE THREAD

**Issue by manigorsh** [bradmartin/nativescript-floatingactionbutton#61]
Tested on AVD and on real devices there is same problem. Here is screenshot with two devices (on the left Android 5.1 and on the right Android 8.0).

![fab on android 5 1 and 8](https://user-images.githubusercontent.com/16129505/31371018-82130672-ad97-11e7-8efb-5a21543bb587.png)

Log:

`JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: createNativeView android ***
JS: ERROR Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
JS:     android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:959)
JS:     android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1007)
JS:     android.graphics.drawable.RippleDrawable$RippleState.<init>(RippleDrawable.java:922)
JS:     android.graphics.drawable.RippleDrawable.<init>(RippleDrawable.java:979)
JS:     android.graphics.drawable.RippleDrawable.<init>(RippleDrawable.java:94)
JS:     android.graphics.drawable.RippleDrawable$RippleState.newDrawable(RippleDrawable.java:944)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:953)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:937)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:929)
JS:     com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:12)
JS:     org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
JS:     org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5254)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`

**Comment by manigorsh** [comment]
As temporary decision for SDK < 26 instead of next code 

`<FAB (tap)="addItem()" row="1" icon="res://ic_add_white" rippleColor="#f1f1f1" class="fab-button"></FAB>`

I show

`<Button row="1" class="fab-button-simple" (tap)="addItem()"></Button>`

and added appropriate css style

`.fab-button-simple {
    height: 70;
    width: 70;
    margin: 15;
    border-radius: 35;
    background-image: url("res://ic_add_white");
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    background-color: #CB1D00;
    horizontal-align: right;
    vertical-align: bottom;
}`

looks not elegant but works for me.

![temporary desision](https://user-images.githubusercontent.com/16129505/31376808-ccec77fc-adae-11e7-85fe-3fccf063ac4a.png)

**Comment by public-virtualys** [comment]
Maybe it is a problem with android support libraries versions. Mine are resolved to 25.3.1, but plugin needs 26.0.1. I didn't find the way to change supportVersion property in gradle project yet. If anybody knows ..
