### ISSUE TITLE
Plugin does not work when running AoT with Angular

### ISSUE THREAD

**Issue by VladimirAmiorkov** [bradmartin/nativescript-floatingactionbutton#65]
This plugin looks to not be supporting Ahead of time compilation when inside an {N} + Angular project. It would be great if this gets resolved as it basically makes using this plugin in production not possible.

**Comment by davorpeic** [comment]
Hey @VladimirAmiorkov,
did you added `registerElement('Fab', () => require('nativescript-floatingactionbutton').Fab);` in main.aot.ts?
I'm running latest {N} with angular and it works fine even with webpack build. Check your versions, normally project upgrade fixes a lots of issues.

**Comment by VladimirAmiorkov** [comment]
@davorpeic Thanks for pointing this out to me, I totally forgot that I was doing manual registering for this plugin.

**Comment by davorpeic** [comment]
@VladimirAmiorkov no worries, I just solved similar issue with this for webpack build so I learned :)
