### ISSUE TITLE
Floating Action Button not working

### ISSUE THREAD

**Issue by charlessabenin** [bradmartin/nativescript-floatingactionbutton#66]
Hi, i am using nativescript with javascript and i am trying to add floating Action Button but it is not working.
After following steps with : [https://github.com/bradmartin/nativescript-floatingactionbutton/blob/master/README.md](url)
i have a white screen and this message : Cannot read property 'FloatinActionButton' of undefined, undefined

can anybody help please!

**Comment by bradmartin** [comment]
Can you share the markup you have? Also the commands executed and if you rebuilt the app?

**Comment by chuckmitchell** [comment]
I Have the same issue, but with {N} Angular/

Do I add the Element registration code to `main.ts,` before the following line?

> platformNativeScriptDynamic().bootstrapModule(AppModule);

This is the code I'm talking about:
> import {registerElement} from "nativescript-angular/element-registry";
> registerElement("FAB", () => require("nativescript-floatingactionbutton").Fab);`
 
I'm getting an error when loading the page stating 

> Cannot read property "FloatingActionButton" of undefined, undefined.

HTML:
https://paste.ofcode.org/UMwk44gTkCtwbR9KfC2dh8

TS:
https://paste.ofcode.org/uFTEYn6wV65LgPG9ZtbKju

**Comment by bradmartin** [comment]
Do it in app.component like the below example from a working production app:

```
import { registerElement } from "nativescript-angular/element-registry";
import { TextInputLayout } from "nativescript-textinputlayout";
registerElement("Fab", () => Fab);
registerElement("MapView", () => MapView);
registerElement("TextInputLayout", () => TextInputLayout);
// tslint:disable-next-line:no-require-imports
registerElement("Gradient", () => require("nativescript-gradient").Gradient);

// app
import { ActionBarUtil } from "./utils";
import * as frescoModule from "nativescript-fresco";

@Component({
  selector: "ns-app",
  template: "<page-router-outlet></page-router-outlet>"
})
```
