### ISSUE TITLE
Angular - hideOnSwipeOfView not working

### ISSUE THREAD

**Issue by ChristianSchroedel** [bradmartin/nativescript-floatingactionbutton#68]
Hi,

I just tried out your FAB plugin. Setting up the fab worked without problems and it is also showing up correctly in my App - Tab also works.

Where I am struggling is to get the property "hideOnSwipeOfView" to work. I set an id on the ListView element I am using to slide out the fab, but with no luck.

I created a sample with the new NativeScript PlayGround:
https://play.nativescript.org/?template=play-ng&id=xwd7M7&v=2

**PS: I just tried it on Android 6+**

Maybe I am just missing something, or I missread the documentation?

Thank you for your help

**Comment by dieien** [comment]
Hi,
same problem here!

I'm trying on a real Android device (7.0).

**Comment by gummibjorn** [comment]
For some reason it doesn't work on the first app-start after installation.

After restarting the app, hiding works fine
