### ISSUE TITLE
Strange sizing issues

### ISSUE THREAD

**Issue by bearoutthere** [bradmartin/nativescript-floatingactionbutton#73]
![screenshot_1525327419](https://user-images.githubusercontent.com/1024870/39562153-555a0f2a-4ed4-11e8-8f6f-46ccb4da11cc.png)
![screenshot_1525327430](https://user-images.githubusercontent.com/1024870/39562156-58fa2c82-4ed4-11e8-928f-ae474f5abccb.png)

Just just added FAB on 2 similar pages inside a grid layout.  Both are set to width and height of 50.  But the size of the button visibly changes between the pages.  Screenshots attached.  Why does the size of FAB changes despite the set width and height?

It also looks like the + icons are too small.  Is there a way to use FontAwesome icons in the FAB rather than providing separate images?

Thanks in advance.

**Comment by bradmartin** [comment]
I'm not sure on the sizing, possibly some other css/styles on the different pages.

As for the images/font/text question - https://github.com/bradmartin/nativescript-floatingactionbutton/issues/53 on Android it's not very simple to do with the native FAB. However, you can always mock a FAB with a `Button` in NS using border-radius, height/width and then you could use font icons with no issue, that's actually a solid approach for most apps and is more flexible IMO. I love the native FAB widget myself but sometimes it's not the best option unfortunately.
