### ISSUE TITLE
Crashes on Mac

### ISSUE THREAD

**Issue by bearoutthere** [bradmartin/nativescript-floatingactionbutton#74]
Page with this component errors out during build for both Android and iOS when building on Mac (VS Code)  but works fine on Ubuntu.

The error says failed to build XML an points to the first line of the fab component: 

`
<FAB:fab tap="fabTap"
                        id="new-report-button" 
                        col="1" row="0"
                        icon="res://ic_add_white"
                        rippleColor="#f1f1f1"
                        backgroundColor="#FF530D" 
                        class="fab-button"
                        isEnabled="{{ selectedPerson.isSelected }}" 
                        tap="createReport" 
                        style="height: 50; width: 50;"
                        marginRight="5"
                        marginBottom="3"
                    />
`

**Comment by bradmartin** [comment]
If plain NS, you likely don't have the xml namespace declared on the `Page`.
