### ISSUE TITLE
fixed position inside scrollview

### ISSUE THREAD

**Issue by peppeg85** [bradmartin/nativescript-floatingactionbutton#77]
hello, as the title says, how fix the button inside a scrollview (the page scrolls but the button is still there)?

thank you !

**Comment by anki247** [comment]
Wrap them inside a GridLayout **with same row**

```html
<GridLayout rows="*">
    <ScrollView row="0">
      ...
    </ScrollView>
    <FAB row="0" ... ></FAB>
</GridLayout>
```
