### ISSUE TITLE
Fixing the position of FAB 

### ISSUE THREAD

**Issue by hrajpal96** [bradmartin/nativescript-floatingactionbutton#78]
The FAB positioning faces an issue if position:absolute is used in the corresponding css (say, on the bottom right side of the screen).

**Comment by bradmartin** [comment]
if you want to position it on the bottom right, it's going to be entirely dependent upon your page and the layout you are using. If you want to 'float' it then I suggest a gridlayout seen [here](https://github.com/bradmartin/nativescript-floatingactionbutton#xml) and in the demo app.
