### ISSUE TITLE
Icon Not Loading

### ISSUE THREAD

**Issue by csivaprasadc** [bradmartin/nativescript-floatingactionbutton#82]
I have an icon png image icon8-multiply-50.png under App_Resources/iOS and trying to set it to the icon property of FAB button.

It is not displaying that icon in the FAB button. It is showing only the default plus button from the library.

<FAB row="1" (tap)="fabTap($event)" icon="res://icon8-multiply-50.png" rippleColor="#f1f1f1" class="fab-button">

**Comment by bradmartin** [comment]
I don't think you need to use file extension when referencing image assets (anything with `res://`)

**Comment by csivaprasadc** [comment]
I tried all the options for loading the resources and it did not work.

Thanks and Regards
Sivaprasad Chidambaram

**Comment by csivaprasadc** [comment]
Finally I was able to resolve the issue after doing a platform clean and running the application again.
