### ISSUE TITLE
Icon isn't in the middle of the fab

### ISSUE THREAD

**Issue by ableschulze** [bradmartin/nativescript-floatingactionbutton#84]
HI,

i've an issue with the fab. The icon i chossed isn't showing in the middle of the fab. Can someone help me? This is my code:

```
<grid-layout rows="auto, *">
    <StackLayout row="0" orientation="horizontal" tkExampleTitle tkToggleNavButton>
        <RadListView [items]="chars">
            <ng-template tkListItemTemplate let-item="item">
                <StackLayout orientation="vertical">
                    <Label class="nameLabel" [text]="item.name"></Label>
                    <Label class="descriptionLabel" [text]="item.description"></Label>
                </StackLayout>
            </ng-template>
        </RadListView>
    </StackLayout>
    <FAB  row="1" icon="res://ic_add_white" rippleColor="#f1f1f1" class="fab-button"></FAB>
</grid-layout>
```
![screenshot_1541543760](https://user-images.githubusercontent.com/13657581/48098378-d7a9ef00-e21c-11e8-91c2-9a53acc58dc9.png)

**Comment by ableschulze** [comment]
```
 "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "@fortawesome/fontawesome-free": "^5.5.0",
    "moment": "^2.22.2",
    "nativescript-angular": "~6.1.0",
    "nativescript-floatingactionbutton": "^4.1.4",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-plugin-firebase": "^7.3.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-listview": "3.7.2",
    "nativescript-ui-sidedrawer": "^4.3.1",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.2.0",
    "tns-core-modules": "~4.2.0",
    "tslib": "^1.9.3",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@nativescript/schematics": "~0.3.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.16.0",
    "typescript": "~2.7.2",
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.2.0"
  },
```

**Comment by JosepBergay** [comment]
Same issue here after upgrading to TNS 5.0 and Android SDK 28. Only checked android.

**Comment by NeriCodec** [comment]
Hello, I have the same behavior once updated to version 5.0.0 update the tns-core-module but still you got the problem, I had to go back to version 4.2.0 because several plugins stopped working.

**Comment by budineverend** [comment]
> Same issue here after upgrading to TNS 5.0 and Android SDK 28. Only checked android.
> EDIT: @ableschulze try upgrading tns-core-modules. I tested it in a new project and that fixed it.

could you example for me?
i also get the problem and i dont why position at right top(i want right bottom), thanks..

**Comment by NeriCodec** [comment]
@budineverend  what version of Nativescript `tns-android` you have install ?

**Comment by budineverend** [comment]
> That is super weird 😕 . I've never seen that. The placement of the image resource is handled on android entirely by the native component, nothing in the plugin should alter it in any way. That is what is confusing.
> 
> Maybe make sure you have the latest Android support libraries and SDKs and rebuild the project entirely to see if this was a bug in the android lib at one point.

please help it..
i also get same the error..

**Comment by bradmartin** [comment]
I'd love to help for sure, just not sure what's causing the problem. I don't think it's related to the source code of the FAB.

@budineverend - can you share your package.json, be sure to remove any private info (like app name if you can't share that). This will help determine any conflicts in dependencies that might be causing erratic behavior.

**Comment by budineverend** [comment]
this is my package.json..

  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "^6.2.0",
    "nativescript-background-http": "^3.3.0",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-floatingactionbutton": "^4.1.4",
    "nativescript-imagepicker": "^6.0.4",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-sidedrawer": "~5.0.0",
    "nativescript-webview-interface": "^1.4.2",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.2.0",
    "tns-core-modules": "^5.0.2",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0",
    "@nativescript/schematics": "~0.3.0",
    "@ngtools/webpack": "~6.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.17.0",
    "tslint": "~5.11.0",
    "typescript": "~2.7.2"
  }

**Comment by budineverend** [comment]
> @budineverend what version of Nativescript `tns-android` you have install ?

I am using NS 5.0.0 now..

**Comment by bradmartin** [comment]
For those interested: https://github.com/bradmartin/nativescript-floatingactionbutton/blob/a6b2cbb171dc78ee9cd3279a6602b416e802a9e8/src/fab.android.ts#L36 - I'm using the suggested 24dp for icons in the demo app and centering the icon with no scaling fixed the demo app 👍 so expect same results once everyone bumps to 5.0.0 of this plugin. 

I bumped major bc we are also bumping 2 versions on the default of the support lib version, so I wanted to be cautious of breaking changes android has from 26x -> 28x
