### ISSUE TITLE
Version 5.0.2 is empty and does not contain any .js files

### ISSUE THREAD

**Issue by VladimirAmiorkov** [bradmartin/nativescript-floatingactionbutton#92]
Hi,

After upgrading to 5.0.2 from 5.0.1 I notice that the package actually does not have any implementation files in it (.js files) it contains:

- README.md
- platforms
- package.json
- index.d.ts

Maybe this was a corrupted package which was published yesterday?

To reproduce simple do `npm i nativescript-floatingactionbutton`

**Comment by bradmartin** [comment]
thanks @VladimirAmiorkov - 5.0.3 should have the files correct
