### ISSUE TITLE
Unclear how to use instruction.

### ISSUE THREAD

**Issue by Arthur-Kamau** [bradmartin/nativescript-floatingactionbutton#94]
From the sample app, and the instruction its unclear on which files should be edited.Especially for beginners.
It would be really helpful to list in detail the steps taken for example in angular should there be an import in the @NgModule or where should i input the code provided for Angular.
Also wouldn't be helpful to get an example for each ie Angular, Vue and Typescript.

**Comment by bradmartin** [comment]
Angular steps are on the README [here](https://github.com/bradmartin/nativescript-floatingactionbutton#nativescript-angular) 

Feel free to add a PR adding a demo project for angular.
